+PGs Seperated.

diff --git a/.github/workflows/dev2-test.yaml b/.github/workflows/dev2-test.yaml
--- a/.github/workflows/dev2-test.yaml
+++ b/.github/workflows/dev2-test.yaml
@@ -2,6 +2,18 @@ name: Run Playwright Tests on Dev2
 
 on:
   workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Choose the environment'
+        required: true
+        default: 'Moyasar'
+        type: choice
+        options:
+          - Moyasar
+          - Tyro
+          - Tuna
+          - Checkout
+          - Adyen
 
 jobs:
   test:
@@ -9,8 +21,8 @@ jobs:
 
     strategy:
       matrix:
-        shard: [1/2, 2/2]  
-
+        shard: [1/2, 2/2]
+    
     steps:
       - name: Cache node modules
         uses: actions/cache@v3
@@ -29,7 +41,19 @@ jobs:
       - name: Install Playwright browsers and dependencies
         run: npx playwright install --with-deps
 
+      - name: Choose Playwright config
+        run: |
+          case ${{ github.event.inputs.environment }} in
+            Moyasar) config="configs/playwright.config-dev2Moyasar.js";;
+            Tyro) config="configs/playwright.config-dev2Tyro.js";;
+            Tuna) config="configs/playwright.config-dev2Tuna.js";;
+            Checkout) config="configs/playwright.config-dev2Checkout.js";;
+            Adyen) config="configs/playwright.config-dev2Adyen.js";;
+            *) echo "Invalid environment" && exit 1;;
+          esac
+          echo "Using config $config"
+
       - name: Run Playwright tests for shard ${{ matrix.shard }}
         run: |
-          echo "Running shard ${{ matrix.shard }}"
-          npx playwright test --config=playwright.config2.js --project=chromium --shard=${{ matrix.shard }}
+          echo "Running shard ${{ matrix.shard }} with config $config"
+          npx playwright test --config=$config --project=chromium --shard=${{ matrix.shard }}
